RubyOnRails-master/config/routes.rb
Rails.application.routes.draw do
  resources :items

  resources :lists
    get 'lists/move_up'
    get 'lists/move_down'

  root :to => "lists#new"

end

RubyOnRails-master/app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
  acts_as_list :scope => :list_id

end

RubyOnRails-master/app/models/list.rb
class List < ActiveRecord::Base
  has_many :items
  List.order(created_at: :desc)
end

RubyOnRails-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

RubyOnRails-master/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @list=List.find_by_id(params[:id])
    @item =@list.items.build

  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @list = List.find_by_id(params[:id])
    @item=@list.items.build(params.require(:item).permit(:name, :status))

    respond_to do |format|
      if @item.save
        format.html { redirect_to new_list_path, notice: 'Item was successfully created.'}
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to new_list_path, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to new_list_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def move_up
    @item=Item.find(params[:id])
    @foo=@item.list_id
    @item.decrement_position
    redirect_to items_path(foo_param: @foo), notice: 'Todo item was successfully moved up.'
  end

  def move_down

    @item=Item.find(params[:id])
    @foo=@item.list_id
    @item.increment_position
    redirect_to items_path(foo_param: @foo), notice: 'Todo item was successfully moved down.'
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :status)
    end
end

RubyOnRails-master/app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list=List.new
    @lists=List.all
  end
  def move_up
    @list=List.find(params[:id])
    @foo=@list
    @list.decrement_position
    redirect_to list_path(foo_param: @foo), notice: 'Todo List was successfully moved up.'
  end

  def move_down

    @list=List.find(params[:id])
    @foo=@list
    @list.increment_position
    redirect_to list_path(foo_param: @foo), notice: 'Todo List was successfully moved down.'
  end




  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list=List.new(params.require(:list).permit(:name))
    @lists=List.all

    respond_to do |format|
      if @list.save
        format.html { redirect_to new_list_path, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to new_list_path, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to new_list_path, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name)
    end


end

RubyOnRails-master/app/helpers/application_helper.rb
module ApplicationHelper
end

RubyOnRails-master/app/helpers/items_helper.rb
module ItemsHelper
end

RubyOnRails-master/app/helpers/lists_helper.rb
module ListsHelper
end

RubyOnRails-master/app/views/items/_form.html.erb
<%= form_for @item, :html => { :class => "form-horizontal item" } do |f| %>

    <% if @item.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@item[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :status, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :status, :class => 'form-control' %>
    </div>
    <%= error_span(@item[:status]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            items_path, :class => 'btn btn-default' %>

<% end %>

RubyOnRails-master/app/views/items/edit.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

RubyOnRails-master/app/views/items/index.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.id, item_path(item) %></td>
        <td><%= item.name %></td>
        <td><%= item.status %></td>
        <td><%=l item.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_item_path(item), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      item_path(item),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_item_path,
            :class => 'btn btn-primary' %>

RubyOnRails-master/app/views/items/new.html.erb
List: <%= @list.name %> (<%= link_to "back",new_list_path %>)

<hr />
<%= form_for @item, :url => { :action => :create, :id => @list.id } do |f| -%>
    Name: <%= f.text_field :name %> <br />
    Status: <%= f.text_field :status%>  <br />
    <%= f.submit %>
<% end -%>

<hr />

<% if @list.items.exists? %>
    <table border =1 class="table table-striped">
      <tr>
        <th>Name </th>
        <th>Status</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>

      </tr>
      <% for item in @list.items %>
          <% if !item.name.nil? %>
              <tr>
                <td><%=  item.name %></td>
                <td><%= item.status %></td>
                <td><%= link_to "Edit", :controller => :items, :action => :edit,:id =>item.id %></td>
                <td><%= link_to "Delete",:controller => :items, :action => :destroy, :id =>item.id%></td>

                <td><%= link_to "Move_up", :controller => :lists, :action => :move_up,:id =>item.id %></td>

                <td><%= link_to "Move_down",lists_move_down_path, :id =>item.id%></td>

              </tr>
          <% end %>
      <% end %>

    </table>
<% else %>
    No Items yet
<% end %>

RubyOnRails-master/app/views/items/show.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @item.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @item.status %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              items_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_item_path(@item), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              item_path(@item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

RubyOnRails-master/app/views/lists/_form.html.erb
<%= form_for @list, :html => { :class => "form-horizontal list" } do |f| %>

    <% if @list.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@list[:name]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            lists_path, :class => 'btn btn-default' %>

<% end %>

RubyOnRails-master/app/views/lists/edit.html.erb
<%- model_class = List -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

RubyOnRails-master/app/views/lists/index.html.erb
<%- model_class = List -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
  <ul>
    <% @lists.each do |list| %>
        <li>
      <tr>
        <td><%= link_to list.id, list_path(list) %></td>
        <td><%= list.name %></td>
        <td><%=l list.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_list_path(list), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      list_path(list),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
        </li>
    <% end %>
  </ul>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_list_path,
            :class => 'btn btn-primary' %>

RubyOnRails-master/app/views/lists/new.html.erb
<%- model_class = List -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
List names: <br />
<% if !@list.blank? %>
    <table border =1 class="table table-striped">
      <tr>
        <th>Name </th>
        <th></th>
        <th></th>
      </tr>
      <% for item in @lists %>
         <tr>
            <td><%= link_to item.name, :controller => :items, :action => :new, :id =>item.id %></td>
           <td><%= link_to "Edit", :controller => :lists, :action => :edit,:id =>item.id %></td>
           <td><%= link_to "Delete",:controller => :lists, :action => :destroy, :id =>item.id%></td>

            </tr>
      <% end %>
    </table>
<% else %>
    No List yet
<% end %>

<%= render :partial => 'form' %>

RubyOnRails-master/app/views/lists/show.html.erb
<%- model_class = List -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @list.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              lists_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_list_path(@list), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              list_path(@list),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>