lab4/config/routes.rb
Rails.application.routes.draw do
  resources :listtodos

end

lab4/app/models/listtodo.rb
class Listtodo < ActiveRecord::Base
end

lab4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

lab4/app/controllers/listtodos_controller.rb
class ListtodosController < ApplicationController
  before_action :set_listtodo, only: [:show, :edit, :update, :destroy]

  # GET /listtodos
  # GET /listtodos.json
  def index
    @listtodos = Listtodo.all
  end

  # GET /listtodos/1
  # GET /listtodos/1.json
  def show
  end

  # GET /listtodos/new
  def new
    @listtodo = Listtodo.new
  end

  # GET /listtodos/1/edit
  def edit
  end

  # POST /listtodos
  # POST /listtodos.json
  def create
    @listtodo = Listtodo.new(listtodo_params)

    respond_to do |format|
      if @listtodo.save
        format.html { redirect_to @listtodo, notice: 'Listtodo was successfully created.' }
        format.json { render :show, status: :created, location: @listtodo }
      else
        format.html { render :new }
        format.json { render json: @listtodo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listtodos/1
  # PATCH/PUT /listtodos/1.json
  def update
    respond_to do |format|
      if @listtodo.update(listtodo_params)
        format.html { redirect_to @listtodo, notice: 'Listtodo was successfully updated.' }
        format.json { render :show, status: :ok, location: @listtodo }
      else
        format.html { render :edit }
        format.json { render json: @listtodo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listtodos/1
  # DELETE /listtodos/1.json
  def destroy
    @listtodo.destroy
    respond_to do |format|
      format.html { redirect_to listtodos_url, notice: 'Listtodo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listtodo
      @listtodo = Listtodo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listtodo_params
      params.require(:listtodo).permit(:todo, :due)
    end
end

lab4/app/helpers/application_helper.rb
module ApplicationHelper
end

lab4/app/helpers/listtodos_helper.rb
module ListtodosHelper
end

lab4/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lab4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

lab4/app/views/listtodos/_form.html.erb
<%= form_for(@listtodo) do |f| %>
  <% if @listtodo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listtodo.errors.count, "error") %> prohibited this listtodo from being saved:</h2>

      <ul>
      <% @listtodo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :todo %><br>
    <%= f.text_field :todo %>
  </div>
  <div class="field">
    <%= f.label :due %><br>
    <%= f.text_field :due %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

lab4/app/views/listtodos/edit.html.erb
<h1>Editing Listtodo</h1>

<%= render 'form' %>

<%= link_to 'Show', @listtodo %> |
<%= link_to 'Back', listtodos_path %>

lab4/app/views/listtodos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Listtodos</h1>

<table>
  <thead>
    <tr>
      <th>Todo</th>
      <th>Due</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listtodos.each do |listtodo| %>
      <tr>
        <td><%= listtodo.todo %></td>
        <td><%= listtodo.due %></td>
        <td><%= link_to 'Show', listtodo %></td>
        <td><%= link_to 'Edit', edit_listtodo_path(listtodo) %></td>
        <td><%= link_to 'Destroy', listtodo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listtodo', new_listtodo_path %>

lab4/app/views/listtodos/new.html.erb
<h1>New Listtodo</h1>

<%= render 'form' %>

<%= link_to 'Back', listtodos_path %>

lab4/app/views/listtodos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Todo:</strong>
  <%= @listtodo.todo %>
</p>

<p>
  <strong>Due:</strong>
  <%= @listtodo.due %>
</p>

<%= link_to 'Edit', edit_listtodo_path(@listtodo) %> |
<%= link_to 'Back', listtodos_path %>